name: 'Setup Divvun'
description: ''
inputs:
  key:
    description: 'Divvun CI Config Encryption Key'
    required: true
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
